name: Build Android & Deploy & Release and Pages builder

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-deploy:
    name: 'Build & Deploy web app'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.16.5'
      - name: 'Flutter enable Web'
        run: flutter config --enable-web
      - name: 'Get dependencies'
        run: flutter pub get
      - name: 'Build web app'
        run: |
          flutter build web --base-href='/blackhole/web/' --web-renderer=canvaskit --release
      - run: flutter build apk

      # Add the Sign APK step here
      - name: Sign APK
        id: sign_apk
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: build/app/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNINGKEYBASE64 }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTOREPASSWORD }}
          keyPassword: ${{ secrets.KEYPASSWORD }}

      - name: Android Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/app/outputs/apk/release/app-release.apk

      - run: mkdir docs
      - run: mv build/app/outputs/apk/release/app-release.apk docs/
      - run: cp index.html docs/
      - run: cp README.md docs/
      - run: cp ./android/app/src/main/res/mipmap-hdpi/ic_launcher.png docs/
      - uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: docs/
      - run: mkdir upload
      - run: cp -r build/web upload/
      - run: cp -r docs upload/
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: upload

  build-and-release-windows:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.16.5'
      - name: Install project dependencies
        run: flutter pub get
      - name: Generate intermediates
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Enable windows build
        run: flutter config --enable-windows-desktop
      - name: Build artifacts
        run: flutter build windows --release
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: Blackhole-windows.zip
          directory: build/windows/runner/Release
      - name: Create MSIX Package
        uses: Microsoft/create-msix@v2
        with:
          output-directory: build/msix
          package-name: Blackhole
          package-display-name: "Blackhole"
          package-version: ${{ github.ref_name }}
          package-publisher-display-name: "Your Publisher Name"
          package-publisher-id: "Your Publisher ID"
          package-description: "Your app description"
          package-icon: path/to/your/icon.png
      - name: Windows Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/msix/Blackhole.msix
          recreate: true  # 'with msix' is not a valid parameter, change it to 'true'

      - run: mkdir docs
      - run: mv build/app/outputs/apk/release/app-release.apk docs/
      - run: mv build/msix/Blackhole.msix docs/
      - run: cp index.html docs/
      - run: cp README.md docs/
      - run: cp ./android/app/src/main/res/mipmap-hdpi/ic_launcher.png docs/
      - uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: docs/
      - run: mkdir upload
      - run: cp -r build/web upload/
      - run: cp -r docs upload/
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: upload
